load(
    "@rules_dotnet//dotnet:defs.bzl",
    "csharp_binary",
)

csharp_binary(
    name = "app",
    srcs = ["Program.cs"],
    target_frameworks = ["net9.0"],
    project_sdk = "web",
    appsetting_files = [
        "appsettings.json",
    ] + glob(["appsettings.*.json"]),
    deps = [
        "//Features/Users:users",
        "//Features/Publications:publications",
        "//Features/Auth:auth",
        "//Features/Comments:comments",
        "//Features/Core:core",
        "@paket.main//microsoft.aspnetcore.openapi",
        "@paket.main//microsoft.openapi",
        "@paket.main//microsoft.entityframeworkcore.inmemory",
        "@paket.main//microsoft.aspnetcore.authentication.jwtbearer",
        "@paket.main//microsoft.identitymodel.tokens",
        "@paket.main//swashbuckle.aspnetcore.swaggerui",
       
    ],
    run_analyzers = False
)
